# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoPipingServer < Formula
  desc "Piping Server written in Go language"
  homepage "https://github.com/nwtgck/go-piping-server"
  version "0.4.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/nwtgck/go-piping-server/releases/download/v0.4.0/go-piping-server-0.4.0-darwin-arm64.tar.gz"
      sha256 "368e3a55b95f2ae9f61dfa2ccc8f1158521710e92d0c5ab040b3e4b34d23a4fa"

      def install
        bin.install "go-piping-server"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nwtgck/go-piping-server/releases/download/v0.4.0/go-piping-server-0.4.0-darwin-amd64.tar.gz"
      sha256 "c2cda1d617365c22e773acebe60c19bfc8030acad74627208878b46f93e12c7a"

      def install
        bin.install "go-piping-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/nwtgck/go-piping-server/releases/download/v0.4.0/go-piping-server-0.4.0-linux-amd64.tar.gz"
      sha256 "ed01cf440988ba9bfa94b6ab7c32d85064ce461057caa65c4a3769e73cd95b35"

      def install
        bin.install "go-piping-server"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nwtgck/go-piping-server/releases/download/v0.4.0/go-piping-server-0.4.0-linux-arm64.tar.gz"
      sha256 "a5499f354afefeffb4f06149bbf89c056ea22d6e33f0ecb0bec7e2f361842775"

      def install
        bin.install "go-piping-server"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/nwtgck/go-piping-server/releases/download/v0.4.0/go-piping-server-0.4.0-linux-armv6.tar.gz"
      sha256 "d4661e61c17530ccedd9be25bc5e5610d7b9ed300d8a0f9adcd6cf30d98056e0"

      def install
        bin.install "go-piping-server"
      end
    end
  end
end
