# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PipingServer < Formula
  desc "Piping Server written in Go language"
  homepage "https://github.com/nwtgck/go-piping-server"
  version "0.1.1-release-trigger1"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/nwtgck/go-piping-server/releases/download/v0.1.1-release-trigger1/piping-server-0.1.1-release-trigger1-darwin-amd64.tar.gz"
    sha256 "70b79c9d1f9186f5c86944fda00f2d6eafa0d2d31e2363e7a9cf3e2c73241ac4"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/nwtgck/go-piping-server/releases/download/v0.1.1-release-trigger1/piping-server-0.1.1-release-trigger1-darwin-arm64.tar.gz"
    sha256 "2512169ce5c9a8af23d49b93454314cd4c8ddc652149224c8ca825d780285fbd"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/nwtgck/go-piping-server/releases/download/v0.1.1-release-trigger1/piping-server-0.1.1-release-trigger1-linux-amd64.tar.gz"
    sha256 "b9026038a5f858018a3b81890be30dbb75313d850a997637cc6a3e269ce1c9ea"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/nwtgck/go-piping-server/releases/download/v0.1.1-release-trigger1/piping-server-0.1.1-release-trigger1-linux-armv6.tar.gz"
    sha256 "a9ee5aba7420490c496015be6bf963de271915911c77926b31d3869a83b1e2ab"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/nwtgck/go-piping-server/releases/download/v0.1.1-release-trigger1/piping-server-0.1.1-release-trigger1-linux-arm64.tar.gz"
    sha256 "715c8a0aa16d99ebf8b0b5a8caa3de319f4ee78202f0ac0f6e6ddff8bc689bfe"
  end

  def install
    bin.install "piping-server"
  end
end
